### 1. What is a Python library? Why do we use Python libraries?

In [2]:
# A Python library is a collection of modules and packages having different functionalities
# library can be used by other programs or developers.
# Libraries can be easily imported and utilized in Python scripts,which enables user to use the available functions which 
# saves the time and increase productivity.

# Examples of libraries
# NumPy, Pandas, Matplotlib, TensorFlow, Flask, and requests and many more.

# usage / purpose of using libraries:

# Code Reusability: Libraries consists reusable code, allowing developers to use existing solutions rather than writing 
# new code. This promotes code reusability and helps save time and effort.

# Productivity: Libraries provide ready-to-use functions,
# This allows users to focus on solving specific problems rather than wasting time on low-level details.

# Performance: Many popular Python libraries are implemented in low-level languages like C or C++, provides 
#efficient and optimized code and performance.


### 2. What is the difference between Numpy array and List?

In [3]:
# Python lists are hetereogeneous, we can have elements of different data types. 
# For example, a list can contain integers, floats, strings, and other types in the same list.
#whereas NumPy arrays are homogeneous, meaning all elements must be of the same data type.This homogeneity allows 
#for more efficient storage and operations.

# NumPy arrays are more efficient in terms of memory usage and execution speed compared to Python lists. 
# Lists are more flexible but may be less efficient for large-scale numerical computations.

# NumPy provides a various mathematical functions and operations that can be applied to entire arrays. 
#Lists provide fewer built-in operations for mathematical computations.

### 3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [8]:
import numpy as np
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
print("shape of an array: ", arr1.shape)
print("Dimension of an array: ", arr1.ndim)

shape of an array:  (3, 4)
Dimension of an array:  2


### 4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [9]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
print("first row of array is:", arr[0])

first row of array is: [1 2 3 4]


### 5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [10]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
print("Element at 3rd row and 4th column of array is:", arr[2][3])

Element at 3rd row and 4th column of array is: 12


### 6. Write code to extract all odd indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [11]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
print("All odd elements in array are:", arr[arr % 2 != 0])

All odd elements in array are: [ 1  3  5  7  9 11]


### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [18]:
random_mat = np.random.rand(3, 3)
print(random_mat)

[[0.18974896 0.85616538 0.23801681]
 [0.71836147 0.74666034 0.67623225]
 [0.63117758 0.91363395 0.31830232]]


### 8. Describe the difference between np.random.rand and np.random.randn?

In [21]:
# np.random.rand generates random numbers from a uniform distribution over the interval [0, 1).
# whereas np.random.randn generates random numbers from a standard normal distribution 
# with a mean of 0 and a standard deviation of 1.

#ex. 
print("output of np.random.rand\n", np.random.rand(3, 3))
print("*"*40)
print("output of np.random.randn\n", np.random.randn(3, 3))

output of np.random.rand
 [[0.99484523 0.85255194 0.83220012]
 [0.33263133 0.86552383 0.03870795]
 [0.51339832 0.92771954 0.34183163]]
****************************************
output of np.random.randn
 [[-0.40857885  0.52219935  0.02085623]
 [-2.49976767  1.08485805 -0.17552175]
 [-0.73178985  0.28686431 -0.71584602]]


### 9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [30]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

print("Original 1D array:\n", arr)

print("Array after increasing dimension:\n", np.expand_dims(arr, axis=1))

Original 1D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array after increasing dimension:
 [[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


### 10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [31]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

print("array before transpose\n", arr)

print("output of array transpose\n", arr.T)

array before transpose
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
output of array transpose
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide Matrix B by A

In [40]:
matrixA = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
matrixB = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

print("Index wise multiplicaton: \n", matrixA * matrixB)
print("\n Matrix multiplicaton: \n", matrixA.dot(matrixB.T))
print("\n Matrix Addition: \n", matrixA + matrixB)
print("\n substract Matrix B from A: \n", matrixA - matrixB)
print("\n Divide Matrix B by A", matrixB / matrixA)

Index wise multiplicaton: 
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

 Matrix multiplicaton: 
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

 Matrix Addition: 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

 substract Matrix B from A: 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

 Divide Matrix B by A [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 12.  Which function in Numpy can be used to swap the byte order of an array?

In [46]:
# In NumPy, the function np.ndarray.byteswap can be used to swap the byte order of an array.

#ex.
# Create an array with a specified byte order
original_array = np.array([1, 2, 3, 4], dtype=np.int32) 

# Swap the byte order using byteswap
swapped_array = original_array.byteswap(inplace=False)

# Display the output
print("Original Array:", original_array)
print("Swapped Array:", swapped_array)


Original Array: [1 2 3 4]
Swapped Array: [16777216 33554432 50331648 67108864]


### 13.  What is the significance of the np.linalg.inv function?

In [7]:
# np.linalg.inv is used to compute the inverse matrix in Python.
# The resulting matrix, when multiplied by the original matrix, gives the identity matrix.
import numpy as np

# Create a 2x2 matrix
A = np.array([[4, 7],
              [2, 6]])

# Calculate the inverse of the matrix
A_inv = np.linalg.inv(A)

# Display the original and inverse matrices
print("Original Matrix:\n", A)
print("\nInverse Matrix:\n", A_inv)


Original Matrix:
 [[4 7]
 [2 6]]

Inverse Matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


### 14. What does the np.reshape function do, and how is it use?

In [10]:
# The np.reshape function in NumPy is used to change the shape of an array.
# It maintains the total number of elements. 
# The reshaping is done without modifying the original array; instead, a new array with the desired shape is returned.

#e.g.

orig_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = np.reshape(orig_array, (2, 3))

print("Original Array:\n", orig_array)

print("\nReshaped Array:\n",reshaped_array)


Original Array:
 [1 2 3 4 5 6]

Reshaped Array:
 [[1 2 3]
 [4 5 6]]


### 5. What is broadcasting in Numpy?

In [17]:
# Broadcasting in NumPy is a way that allows NumPy to perform operations on arrays of different shapes
# and sizes.
# generally the smaller array is “broadcast” across the larger array so that they have compatible shapes 
# It does this without explicitly creating copies of the data.

# e.g.

arr = np.array([1, 2, 3])
b = 5
arr * b

array([ 5, 10, 15])